// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOVUzUfC1EItHaW21DYLljd8P786Kq8Y',
    appId: '1:1002084503352:web:4a54ef17d73ce7bc3e7bcd',
    messagingSenderId: '1002084503352',
    projectId: 'test1-7a65d',
    authDomain: 'test1-7a65d.firebaseapp.com',
    storageBucket: 'test1-7a65d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgCew8fCqO3vIxuhk2qwCXfKg_1HD9YU',
    appId: '1:1002084503352:android:41cf99af677f42da3e7bcd',
    messagingSenderId: '1002084503352',
    projectId: 'test1-7a65d',
    storageBucket: 'test1-7a65d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Nc0SpIoWWjvGUiGB_5HPIPwFh5X5ORU',
    appId: '1:1002084503352:ios:60d4661692d6c2b03e7bcd',
    messagingSenderId: '1002084503352',
    projectId: 'test1-7a65d',
    storageBucket: 'test1-7a65d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Nc0SpIoWWjvGUiGB_5HPIPwFh5X5ORU',
    appId: '1:1002084503352:ios:60d4661692d6c2b03e7bcd',
    messagingSenderId: '1002084503352',
    projectId: 'test1-7a65d',
    storageBucket: 'test1-7a65d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvOVUzUfC1EItHaW21DYLljd8P786Kq8Y',
    appId: '1:1002084503352:web:7ec21d34f880455b3e7bcd',
    messagingSenderId: '1002084503352',
    projectId: 'test1-7a65d',
    authDomain: 'test1-7a65d.firebaseapp.com',
    storageBucket: 'test1-7a65d.firebasestorage.app',
  );
}
